import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  root: {
    height: '100%',
    display: 'grid',
    gridTemplateColumns: '48px 300px minmax(520px, 1fr) 360px',
    background: 'var(--bg-window)',
    color: 'var(--text-primary)',
    overflow: 'hidden',
    fontFamily: 'var(--font-sans, Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif)',
  },
  activityBar: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 18,
    paddingTop: 14,
    background: 'var(--bg-titlebar)',
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: 'var(--border-subtle)',
  },
  activityIcon: { color: 'var(--text-secondary)' },
  activityIconActive: { color: 'var(--accent-primary)' },
  sourcesPane: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    overflow: 'hidden',
    background: 'var(--bg-chrome)',
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: 'var(--border-subtle)',
    padding: 10,
    gap: 8,
  },
  paneHeader: {
    minHeight: 30,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: 'var(--text-primary)',
    fontSize: 13,
    fontWeight: 700,
  },
  countBadge: {
    minWidth: 22,
    height: 20,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    background: 'var(--bg-card)',
    color: 'var(--text-secondary)',
    fontSize: 11,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--border-subtle)',
  },
  primaryButton: {
    gridColumn: '1 / -1',
    height: 34,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--accent-primary) 70%, transparent)',
    borderRadius: 8,
    color: 'white',
    background: 'var(--accent-primary)',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: 13,
  },
  searchBox: {
    height: 32,
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    padding: '0 9px',
    borderRadius: 8,
    background: 'var(--bg-window)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--border-subtle)',
    color: 'var(--text-secondary)',
  },
  searchInput: { flex: 1, minWidth: 0, borderWidth: 0, borderStyle: 'none', outline: 'none', background: 'transparent', color: 'var(--text-primary)', fontSize: 12 },
  sidebarComposer: { display: 'grid', gap: 7, padding: 8, borderRadius: 8, background: 'var(--bg-window)', borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-subtle)' },
  sidebarComposerInput: { width: '100%', minHeight: 54, maxHeight: 110, resize: 'vertical', borderWidth: 0, borderStyle: 'none', outline: 'none', background: 'transparent', color: 'var(--text-primary)', font: 'inherit', fontSize: 12, lineHeight: 1.4, padding: 0, display: 'block' },
  sidebarComposerActions: { display: 'flex', flexWrap: 'wrap', gap: 5 },
  compactButton: { height: 24, display: 'flex', alignItems: 'center', gap: 4, borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-default, var(--border-subtle))', background: 'var(--bg-titlebar)', color: 'var(--text-primary)', borderRadius: 6, padding: '0 7px', cursor: 'pointer', fontSize: 11, fontWeight: 600 },
  sectionTitle: {
    marginTop: 8,
    padding: '0 2px',
    fontSize: 10,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    fontWeight: 700,
  },
  workspaceList: { display: 'grid', gap: 2, maxHeight: 94, overflow: 'auto' },
  workspaceButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 30,
    padding: '6px 8px',
    borderRadius: 7,
    borderWidth: 1,
    borderStyle: 'solid',
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: 'transparent',
    borderLeftWidth: 3,
    background: 'transparent',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    textAlign: 'left',
  },
  workspaceButtonActive: {
    borderLeftColor: 'var(--accent-primary)',
    borderTopColor: 'var(--border-subtle)',
    borderRightColor: 'var(--border-subtle)',
    borderBottomColor: 'var(--border-subtle)',
    background: 'var(--bg-selected, color-mix(in srgb, var(--accent-primary) 14%, transparent))',
    color: 'var(--accent-primary)',
  },
  workspaceName: { flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: 12 },
  questGrid: { display: 'grid', gap: 3, maxHeight: 150, overflow: 'auto' },
  questButton: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    width: '100%',
    padding: '7px 8px',
    borderRadius: 7,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    background: 'transparent',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    textAlign: 'left',
  },
  questText: { display: 'grid', gap: 1, minWidth: 0 },
  questTitle: { fontSize: 12, fontWeight: 650, color: 'var(--text-primary)' },
  questGoal: { fontSize: 10.5, color: 'var(--text-secondary)', lineHeight: 1.25 },
  sourceList: { display: 'grid', gap: 3, overflow: 'auto', minHeight: 0 },
  sourceItem: {
    display: 'grid',
    gridTemplateColumns: '16px minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 8,
    minHeight: 30,
    padding: '6px 8px',
    borderRadius: 7,
    borderWidth: 1,
    borderStyle: 'solid',
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: 'transparent',
    background: 'transparent',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    textAlign: 'left',
  },
  sourceItemActive: {
    borderTopColor: 'var(--accent-primary)',
    borderRightColor: 'var(--accent-primary)',
    borderBottomColor: 'var(--accent-primary)',
    borderLeftColor: 'var(--accent-primary)',
    background: 'color-mix(in srgb, var(--accent-primary) 12%, transparent)',
  },
  sourceName: { minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: 12 },
  sourceKind: { color: 'var(--text-secondary)', fontSize: 10 },
  centerPane: { display: 'grid', gridTemplateRows: '46px minmax(0, 1fr) 24px', minWidth: 0, overflow: 'hidden', background: 'var(--bg-window)' },
  editorHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    padding: '8px 14px',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--border-subtle)',
  },
  headerIdentity: { display: 'flex', alignItems: 'center', gap: 10, minWidth: 0 },
  headerCopy: { minWidth: 0 },
  headerTitle: { fontSize: 14, fontWeight: 700, color: 'var(--text-primary)', lineHeight: 1.25 },
  headerSubtitle: { marginTop: 1, color: 'var(--text-secondary)', fontSize: 11, lineHeight: 1.25, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 560 },
  headerActions: { display: 'flex', alignItems: 'center', gap: 8, flex: '0 0 auto' },
  statusChip: {
    height: 24,
    display: 'inline-flex',
    alignItems: 'center',
    borderRadius: 999,
    padding: '0 8px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--border-subtle)',
    background: 'var(--bg-titlebar)',
    color: 'var(--text-secondary)',
    fontSize: 11,
    whiteSpace: 'nowrap',
  },
  runButton: {
    height: 30,
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--accent-primary) 70%, transparent)',
    borderRadius: 7,
    padding: '0 11px',
    color: 'white',
    background: 'var(--accent-primary)',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  error: { margin: '10px 14px 0', padding: 9, borderRadius: 8, background: 'rgba(239,68,68,0.12)', color: 'var(--accent-error)', borderWidth: 1, borderStyle: 'solid', borderColor: 'rgba(239,68,68,0.35)', fontSize: 12 },
  ingestPanel: {
    margin: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--border-subtle)',
    background: 'var(--bg-card)',
    overflow: 'hidden',
  },
  panelHeader: { minHeight: 42, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, padding: '9px 12px', borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: 'var(--border-subtle)', background: 'var(--bg-titlebar)' },
  panelTitleNoMargin: { display: 'flex', alignItems: 'center', gap: 8, fontWeight: 700, color: 'var(--text-primary)', fontSize: 13 },
  metaLine: { color: 'var(--text-secondary)', fontSize: 11, lineHeight: 1.3, marginTop: 2, marginBottom: 0 },
  sourceHint: { color: 'var(--text-secondary)', fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.12em', fontWeight: 700 },
  dropInput: { width: '100%', minHeight: 72, resize: 'vertical', borderWidth: 0, borderStyle: 'none', outline: 'none', background: 'var(--bg-input, transparent)', color: 'var(--text-primary)', font: 'inherit', fontSize: 13, lineHeight: 1.5, padding: 12, display: 'block' },
  addButtons: { display: 'flex', flexWrap: 'wrap', gap: 7, padding: '0 12px 12px', background: 'var(--bg-card)' },
  smallButton: { height: 29, display: 'flex', alignItems: 'center', gap: 6, borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-default, var(--border-subtle))', background: 'var(--bg-titlebar)', color: 'var(--text-primary)', borderRadius: 7, padding: '0 9px', cursor: 'pointer', fontSize: 12, fontWeight: 600 },
  editorPanel: { margin: 0, minHeight: 0, display: 'grid', gridTemplateRows: '35px minmax(0, 1fr)', borderRadius: 0, borderWidth: 0, borderStyle: 'solid', borderColor: 'var(--border-subtle)', background: 'var(--bg-card)', overflow: 'hidden' },
  tabBar: { display: 'flex', alignItems: 'center', gap: 10, padding: '0 10px', background: 'var(--bg-titlebar)', borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: 'var(--border-subtle)' },
  activeTab: { height: 34, display: 'inline-flex', alignItems: 'center', color: 'var(--text-primary)', fontSize: 12, fontWeight: 700 },
  tabMeta: { color: 'var(--text-secondary)', fontSize: 11, whiteSpace: 'nowrap' },
  sourceTab: { height: 34, minWidth: 0, maxWidth: 170, display: 'inline-flex', alignItems: 'center', gap: 6, borderWidth: 0, borderStyle: 'none', borderBottomWidth: 2, borderBottomStyle: 'solid', borderBottomColor: 'transparent', background: 'transparent', color: 'var(--text-secondary)', padding: '0 9px', cursor: 'pointer', fontSize: 12 },
  sourceTabActive: { color: 'var(--text-primary)', background: 'var(--bg-card)', borderBottomColor: 'var(--accent-primary)' },
  sourceTabTitle: { minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  emptyEditor: { minHeight: 260, display: 'grid', placeItems: 'center', gap: 10, color: 'var(--text-secondary)' },
  chatBar: { display: 'flex', alignItems: 'center', gap: 9, padding: '8px 14px', borderTopWidth: 1, borderTopStyle: 'solid', borderTopColor: 'var(--border-subtle)', background: 'var(--bg-titlebar)' },
  chatInput: { flex: 1, minWidth: 0, height: 30, borderRadius: 8, borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-subtle)', background: 'var(--bg-window)', color: 'var(--text-primary)', outline: 'none', padding: '0 10px', fontSize: 12 },
  chatButton: { height: 30, borderWidth: 0, borderStyle: 'none', borderRadius: 7, background: 'var(--accent-primary)', color: 'white', padding: '0 12px', fontWeight: 700, cursor: 'pointer' },
  statusBar: { height: 24, display: 'flex', alignItems: 'center', gap: 12, padding: '0 12px', borderTopWidth: 1, borderTopStyle: 'solid', borderTopColor: 'var(--border-subtle)', background: 'var(--bg-titlebar)', color: 'var(--text-secondary)', fontSize: 11, whiteSpace: 'nowrap' },
  statusAccent: { color: 'var(--accent-primary)', fontWeight: 700 },
  statusItem: { overflow: 'hidden', textOverflow: 'ellipsis' },
  statusSpacer: { flex: 1 },
  studioPane: { display: 'flex', flexDirection: 'column', minWidth: 0, overflow: 'hidden', background: 'var(--bg-chrome)', borderLeftWidth: 1, borderLeftStyle: 'solid', borderLeftColor: 'var(--border-subtle)', padding: 12, gap: 10 },
  studioGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  studioTile: { minHeight: 62, display: 'flex', alignItems: 'flex-start', gap: 8, padding: 10, borderRadius: 10, borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-subtle)', background: 'var(--bg-card)', color: 'var(--text-primary)', textAlign: 'left', cursor: 'pointer' },
  studioTileText: { display: 'grid', gap: 3 },
  studioTileTitle: { fontWeight: 700, fontSize: 12 },
  studioTileHint: { color: 'var(--text-secondary)', fontSize: 10.5, lineHeight: 1.25 },
  explorerActions: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6 },
  explorerButton: { height: 30, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-default, var(--border-subtle))', background: 'var(--bg-titlebar)', color: 'var(--text-primary)', borderRadius: 7, padding: '0 8px', cursor: 'pointer', fontSize: 12, fontWeight: 650 },
  explorerDetails: { display: 'grid', gap: 6 },
  detailsSummary: { cursor: 'pointer', color: 'var(--text-secondary)', fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.12em', fontWeight: 700, padding: '2px' },
  agentChatPanel: { display: 'grid', gap: 8, borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-subtle)', borderRadius: 10, padding: 10, background: 'var(--bg-card)' },
  agentChatHint: { color: 'var(--text-secondary)', fontSize: 11, lineHeight: 1.35 },
  agentChatInputRow: { display: 'flex', alignItems: 'center', gap: 7 },
  outputHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginTop: 4 },
  outputList: { display: 'grid', gap: 9, overflow: 'auto', minHeight: 0, flex: 1 },
  outputCard: { borderWidth: 1, borderLeftWidth: 3, borderStyle: 'solid', borderTopColor: 'var(--border-subtle)', borderRightColor: 'var(--border-subtle)', borderBottomColor: 'var(--border-subtle)', borderLeftColor: 'var(--accent-primary)', borderRadius: 8, padding: 10, background: 'var(--bg-window)' },
  outputTitle: { fontWeight: 700, marginBottom: 6, color: 'var(--text-primary)', fontSize: 12 },
  outputPre: { whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0, color: 'var(--text-secondary)', fontSize: 11.5, lineHeight: 1.45, fontFamily: 'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)', maxHeight: 210, overflow: 'auto' },
  outputAction: { marginTop: 8, borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-subtle)', background: 'var(--bg-titlebar)', color: 'var(--text-primary)', borderRadius: 6, padding: '5px 8px', cursor: 'pointer', fontSize: 11 },
  inspectorPanel: { borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-subtle)', borderRadius: 10, padding: 12, background: 'var(--bg-card)', overflow: 'hidden' },
  panelTitle: { display: 'flex', alignItems: 'center', gap: 8, fontWeight: 700, marginBottom: 9, color: 'var(--text-primary)', fontSize: 13 },
  actionButton: { width: '100%', display: 'flex', alignItems: 'center', gap: 8, marginTop: 7, borderRadius: 7, borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-default, var(--border-subtle))', background: 'var(--bg-titlebar)', color: 'var(--text-primary)', padding: '8px 9px', cursor: 'pointer', fontSize: 12 },
  dangerButton: { width: '100%', display: 'flex', alignItems: 'center', gap: 8, marginTop: 7, borderRadius: 7, borderWidth: 1, borderStyle: 'solid', borderColor: 'rgba(239,68,68,0.35)', background: 'rgba(239,68,68,0.08)', color: 'var(--accent-error)', padding: '8px 9px', cursor: 'pointer', fontSize: 12 },
  ghostButton: { borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-subtle)', background: 'var(--bg-titlebar)', color: 'var(--text-secondary)', borderRadius: 6, padding: '4px 7px', cursor: 'pointer', fontSize: 11 },
  muted: { color: 'var(--text-secondary)', fontSize: 12, lineHeight: 1.4 },
};
